/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1816, in to_python
    return int(value)
ValueError: invalid literal for int() with base 10: '506A'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/serializers/python.py", line 135, in Deserializer
    data[field.name] = field.to_python(field_value)
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1821, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ["'506A' value must be an integer."]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 113, in loaddata
    self.load_label(fixture_label)
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 168, in load_label
    for obj in objects:
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/serializers/json.py", line 69, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/home/atgao/.pyenv/versions/inPerson/lib/python3.6/site-packages/django/core/serializers/python.py", line 137, in Deserializer
    raise base.DeserializationError.WithData(e, d['model'], d.get('pk'), field_value)
django.core.serializers.base.DeserializationError: Problem installing fixture '/mnt/c/Users/alice/Documents/school/04 spring 2019/inPerson/inPerson/scraping/course_data.json': ["'506A' value must be an integer."]: (schedule.classes:pk=123) field_value was '506A'
